#include "mech_protocol_cubemars/ak30_force_wire.hpp"

#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <limits>
#include <string>

#include <gtest/gtest.h>

namespace {

using mech::mech_protocol_cubemars::ak10_9_ranges;
using mech::mech_protocol_cubemars::ake60_8_ranges;
using mech::mech_protocol_cubemars::encode_force_control;
using mech::mech_protocol_cubemars::ForceControlCommand;
using mech::mech_protocol_cubemars::ForceControlRanges;
using mech::mech_protocol_cubemars::quantize;

using Payload = std::array<std::uint8_t, 8>;

// Rendering the payload as hex makes a failure legible as a wire frame rather
// than as eight unrelated integer mismatches.
[[nodiscard]] std::string hex(const Payload& payload) {
  std::string out;
  for (std::size_t index = 0; index < payload.size(); ++index) {
    char buffer[4];
    std::snprintf(buffer, sizeof(buffer), "%02X", payload[index]);
    if (index != 0) {
      out.push_back(' ');
    }
    out.append(buffer);
  }
  return out;
}

[[nodiscard]] std::string encoded(const ForceControlCommand& command,
                                  const ForceControlRanges& ranges) {
  Payload payload{};
  EXPECT_TRUE(encode_force_control(command, ranges, payload));
  return hex(payload);
}

// L07 section 4.4's example code states 参数以 AK10-9 为例. Decoding those
// example rows with AKE60-8's ranges gives wrong answers, so every
// manual-derived assertion below uses ak10_9_ranges().
TEST(Ak30ForceWire, ReproducesManualExampleRowsForAk10_9) {
  const auto ranges = ak10_9_ranges();

  // 扭矩 2N, section 4.4.1.
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 0.0, 0.0, 2.0}, ranges),
            "00 00 00 7F FF 7F F8 4B");
  // 扭矩 4N, section 4.4.1.
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 0.0, 0.0, 4.0}, ranges),
            "00 00 00 7F FF 7F F8 97");
  // 速度设置为 -6rad/s with Kd 2, section 4.4.1.
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 2.0, 0.0, -6.0, 0.0}, ranges),
            "00 06 66 7F FF 64 87 FF");
}

// The 速度设置为 6rad/s row reads "00 06 66 7F FF 98 67 FF". DATA[5] should be
// 0x9B: 0x98 decodes to 5.3402 rad/s under AK10-9's +/-28 range. The -6 row
// above is correct, which is what proves the packing right and this cell wrong.
// Copying the manual verbatim would bake in a systematic ~11% velocity error
// that no offline test could otherwise catch.
TEST(Ak30ForceWire, CorrectsTheTranscriptionErrorInThePositiveVelocityRow) {
  const auto ranges = ak10_9_ranges();
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 2.0, 0.0, 6.0, 0.0}, ranges),
            "00 06 66 7F FF 9B 67 FF");
}

// AKE60-8 (L07 p.37): position +/-12.56 rad, velocity +/-40.0 rad/s,
// torque +/-15.0 N.m, Kp 0-500, Kd 0-5. Back-solved, not copied.
TEST(Ak30ForceWire, EncodesAke60_8GoldenVectors) {
  const auto ranges = ake60_8_ranges();

  // Torque sub-mode: gains zero, position and velocity centred.
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 0.0, 0.0, 2.0}, ranges),
            "00 00 00 7F FF 7F F9 10");
  // Velocity sub-mode: Kd only.
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 2.0, 0.0, 6.0, 0.0}, ranges),
            "00 06 66 7F FF 93 27 FF");
  // Position sub-mode: Kp and Kd both set.
  EXPECT_EQ(encoded(ForceControlCommand{100.0, 2.0, 6.0, 0.0, 0.0}, ranges),
            "33 36 66 BD 24 7F F7 FF");
}

TEST(Ak30ForceWire, EncodesRangeBoundariesWithoutOverflow) {
  const auto ranges = ake60_8_ranges();

  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 12.56, 0.0, 0.0}, ranges),
            "00 00 00 FF FF 7F F7 FF");
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, -12.56, 0.0, 0.0}, ranges),
            "00 00 00 00 00 7F F7 FF");
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 0.0, 40.0, 0.0}, ranges),
            "00 00 00 7F FF FF F7 FF");
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 0.0, -40.0, 0.0}, ranges),
            "00 00 00 7F FF 00 07 FF");
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 0.0, 0.0, 15.0}, ranges),
            "00 00 00 7F FF 7F FF FF");
  EXPECT_EQ(encoded(ForceControlCommand{0.0, 0.0, 0.0, 0.0, -15.0}, ranges),
            "00 00 00 7F FF 7F F0 00");
}

// Kp at its maximum quantizes to 4094, not 4095, because the manual's table is
// generated by truncation and 500 * (4095/500) evaluates just below 4095 in
// binary floating point. Kd at its maximum does reach 4095. This asymmetry is
// real and matches the manual; do not "fix" it by rounding, which would break
// the position-zero and velocity-zero rows that pin the truncation behaviour.
TEST(Ak30ForceWire, QuantizesGainMaximaByTruncationLikeTheManualTable) {
  EXPECT_EQ(quantize(500.0, 0.0, 500.0, 12U), 4094U);
  EXPECT_EQ(quantize(5.0, 0.0, 5.0, 12U), 4095U);
  EXPECT_EQ(encoded(ForceControlCommand{500.0, 5.0, 0.0, 0.0, 0.0},
                    ake60_8_ranges()),
            "FF EF FF 7F FF 7F F7 FF");
}

// L07's printed float_to_uint() scales by (1<<bits)/span rather than
// ((1<<bits)-1)/span. Under that formula p_des = P_MAX yields p_int = 65536,
// which does not fit 16 bits: the payload becomes 00 00 and decodes as
// -12.56 rad. Maximum position would command minimum position. This test fails
// loudly if anyone restores the vendor formula.
TEST(Ak30ForceWire, EncodingMaxPositionDoesNotWrapToMinimum) {
  const auto ranges = ake60_8_ranges();
  Payload at_max{};
  Payload at_min{};
  ASSERT_TRUE(encode_force_control(ForceControlCommand{0.0, 0.0, 12.56, 0.0, 0.0},
                                   ranges, at_max));
  ASSERT_TRUE(encode_force_control(ForceControlCommand{0.0, 0.0, -12.56, 0.0, 0.0},
                                   ranges, at_min));
  EXPECT_NE(hex(at_max), hex(at_min));
  EXPECT_EQ(at_max[3], 0xFFU);
  EXPECT_EQ(at_max[4], 0xFFU);
}

// The vendor code clamps out-of-range input. Clamping silently converts an
// invalid command into a valid-looking one, which is exactly the degradation
// ADR-012 forbids. Reject instead.
TEST(Ak30ForceWire, RejectsOutOfRangeInputInsteadOfClamping) {
  const auto ranges = ake60_8_ranges();
  Payload payload{};

  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{0.0, 0.0, 12.57, 0.0, 0.0}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{0.0, 0.0, 0.0, 40.1, 0.0}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{0.0, 0.0, 0.0, 0.0, -15.1}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{500.1, 0.0, 0.0, 0.0, 0.0}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{-0.1, 0.0, 0.0, 0.0, 0.0}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{0.0, 5.1, 0.0, 0.0, 0.0}, ranges, payload));
}

TEST(Ak30ForceWire, RejectsNonFiniteInput) {
  const auto ranges = ake60_8_ranges();
  Payload payload{};
  const double nan_value = std::numeric_limits<double>::quiet_NaN();
  const double inf_value = std::numeric_limits<double>::infinity();

  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{0.0, 0.0, nan_value, 0.0, 0.0}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{0.0, 0.0, 0.0, inf_value, 0.0}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{0.0, 0.0, 0.0, 0.0, -inf_value}, ranges, payload));
  EXPECT_FALSE(encode_force_control(
      ForceControlCommand{nan_value, 0.0, 0.0, 0.0, 0.0}, ranges, payload));
}

TEST(Ak30ForceWire, RejectsDegenerateRanges) {
  Payload payload{};
  const ForceControlRanges zero_position{0.0, 40.0, 15.0, 500.0, 5.0};
  EXPECT_FALSE(zero_position.is_valid());
  EXPECT_FALSE(encode_force_control(ForceControlCommand{}, zero_position,
                                    payload));
}

TEST(Ak30ForceWire, RoundTripsThroughDequantizeWithinOneLeastSignificantBit) {
  using mech::mech_protocol_cubemars::dequantize;
  const auto ranges = ake60_8_ranges();
  const double torque_lsb = (2.0 * ranges.torque_max_nm) / 4095.0;
  const std::uint32_t raw =
      quantize(2.0, -ranges.torque_max_nm, ranges.torque_max_nm, 12U);
  EXPECT_NEAR(dequantize(raw, -ranges.torque_max_nm, ranges.torque_max_nm, 12U),
              2.0, torque_lsb);
}

TEST(Ak30ForceWire, ComposesIdentifiersFromModeAndDriveId) {
  using mech::mech_protocol_cubemars::feedback_can_id;
  using mech::mech_protocol_cubemars::force_control_can_id;
  // motor1: drive id 104 decimal = 0x68.
  EXPECT_EQ(force_control_can_id(104U), 0x0868U);
  EXPECT_EQ(feedback_can_id(104U), 0x2968U);
  EXPECT_EQ(force_control_can_id(0U), 0x0800U);
  EXPECT_EQ(feedback_can_id(255U), 0x29FFU);
}

}  // namespace
