stm32_ctrboard:
  ros__parameters:
    transport: usb_cdc
    device_path: /dev/ttyACM0
    logical_bus: 1
    board_version_major: 4
    board_version_minor: 8
    board_version_patch: 8
    poll_period_ms: 1
    imu_1_frame_id: thigh_imu_link
    imu_2_frame_id: shank_imu_link
